In [2]:
import os
import torch as th

In [26]:
path_train = '../tmp/train_beam.txt'
path_gen = '../tmp/gen_beam.txt'

In [27]:
def read(path):
    lines = []
    with open(path, 'r') as r:
        for line in r.readlines():
            line = line.strip()
            if len(line) > 0:
                lines.append(line)
    assert len(lines) % 2 == 0
    pairs = [(lines[i * 2], lines[i * 2 + 1]) for i in range(len(lines) // 2)]
    return pairs

In [28]:
pairs_train = read(path_train)
pairs_gen = read(path_gen)

In [29]:
pairs_train = sorted(pairs_train)
pairs_gen = sorted(pairs_gen)

In [30]:
for p_t, p_g in zip(pairs_train, pairs_gen):
    if p_t[1] != p_g[1]:
        print(p_t[0], p_t[1], p_g[0], p_g[1], '\n', sep='\n')

184 00: 10: 20,000 UNKNOWNTOKENINREF & gt; 00: 10: 25,000 Also drei sehr schwierige Probleme, die vielleicht lösbar sind Also drei sehr schwierige Probleme, die vielleicht lösbar sind, und an denen man deshalb arbeiten sollte.
Drei sehr schwierige Probleme also, die vielleicht lösbar sind, also sollten wir auch an ihnen arbeiten.
184 00: 10: 20,000 <<unk>> & gt; 00: 10: 25,000 Also drei sehr schwierige Probleme, die vielleicht lösbar sind Also drei sehr schwierige Probleme, die vielleicht lösbar sind, und an denen man deshalb arbeiten sollte.
Drei sehr schwierige Probleme, die vielleicht lösbar sind, also sollten wir auch an ihnen arbeiten.


2.5 zu eins, großartig. UNKNOWNTOKENINREF2.5 zu eins was?
DP: UNKNOWNTOKENINHYPWas?UNKNOWNTOKENINHYP
2.5 zu eins, großartig. <<unk>>2.5 zu eins was?
DP: <unk>Was?<unk> (Applaus)


Aber Energie und Klima sind extrem wichtig für diese Menschen, Genau genommen sogar wichtiger als für jeden anderen auf dem Planeten.
Aber Energie und Klima sind extrem 

In [154]:
debug = th.load('../tmp/debug.pt')
debug2 = th.load('../tmp/debug2.pt')

In [155]:
debug[0].size(), len(debug2)

(torch.Size([512, 5151]), 4)

In [158]:
debug2[3][:, debug[0].size(-1):]

tensor([[-0.0019,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0019,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0009,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [-0.0003,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0007,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0002,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
       device='cuda:0')

In [156]:
(debug[0] - debug2[3][:, :debug[0].size(-1)]).abs().mean()

tensor(0., device='cuda:0')

In [109]:
debug[1][0][:, :80]

tensor([[ 0.3879,  0.8750,  1.9411,  ...,  1.4801,  0.5859,  0.3275],
        [ 0.7662,  0.8837,  0.9721,  ...,  1.6882,  0.7641,  0.5171],
        [ 1.2234,  0.7226,  0.7851,  ...,  0.7384,  0.2003,  0.3806],
        ...,
        [ 0.0580,  0.0350, -0.0330,  ...,  1.0112,  1.0579,  0.4028],
        [-0.0344, -0.1101,  0.2798,  ..., -0.1388, -0.1598, -0.1163],
        [ 1.5007,  0.5233,  1.0698,  ...,  1.7956,  1.8382,  0.6611]])

In [165]:
sample_gen = th.load('../tmp/sample_gen.pt')
sample_train = th.load('../tmp/sample_train.pt')

In [166]:
sample_gen['net_input']['src_tokens']

tensor([[ 2.4414e-04, -9.1553e-05, -3.0518e-04,  ...,  6.3477e-03,
          6.9580e-03,  6.9580e-03],
        [-5.0964e-03, -9.2468e-03, -1.3153e-02,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 1.1292e-03,  1.4038e-03,  8.5449e-04,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 4.5776e-04, -9.4604e-04, -3.9062e-03,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]], device='cuda:0', dtype=torch.float16)

In [167]:
(sample_gen['net_input']['src_tokens'].cpu() - sample_train['net_input']['src_tokens'].cpu()).max()

tensor(0., dtype=torch.float16)

In [168]:
sample_gen['id']

tensor([0, 2, 1, 3], device='cuda:0')

In [197]:
encoder_gen = th.load('../tmp/gen.pt')
encoder_train = th.load('../tmp/train.pt')

In [203]:
(encoder_gen[2] - encoder_train[2]).max()

tensor(0., device='cuda:0', dtype=torch.float16)