In [1]:
import torch as th
import torch.nn as nn
import torch.nn.functional as F

from transformers import MBartForConditionalGeneration, MBart50TokenizerFast

In [2]:
model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50-many-to-one-mmt")
tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-many-to-one-mmt", src_lang="zh_CN", tgt_lang="en_XX")

In [3]:
model2 = th.load('/mnt/raid0/siqi/checkpoints/pretrained/mbart50.ft.n1/model.pt')

In [4]:
input_ids = [250025,      6,  72286,  28226,  58016,  68195, 245543, 118902,   7051, 19752,  13641,     30,      2]
labels = [  250004, 1061,    191,    764,    509,    456,      9,  30962,   3674,    237,        70, 185256,  93324,     47,   8060,    136,    148,  48672,   1810,    19963,     66,      5,      2,      1,      1]

In [5]:
model.eval()
device = 'cuda'
model = model.to(device)
outputs = model(input_ids=th.LongTensor([input_ids]).to(device), labels=th.LongTensor([labels]).to(device), output_hidden_states=True)

In [30]:
outputs.logits.argmax(dim=-1)

tensor([[250004,   1529,    191,   7103,    509,  19574,    162, 140545,   3674,
             70,  47749,  47749,    111,    111,  78431,     70,  78431,  48672,
           1810,  19963,     66,      5,      2, 250004,      5]],
       device='cuda:0')

In [10]:
hf_param = th.load('../tmp/hf.pt')
fs_param = th.load('../tmp/fs.pt')

In [12]:
hf_param[1]

tensor([[[ 0.0385,  0.0989, -0.3345,  ..., -0.4580, -0.7559, -1.5159],
         [-0.4181,  0.1508, -0.2684,  ...,  0.0602,  0.4919,  1.7497],
         [ 1.5350, -0.7008, -0.4443,  ..., -0.0767, -1.3779, -0.2458],
         ...,
         [ 1.0730,  0.2572,  1.5042,  ...,  1.9011, -0.3405,  0.4455],
         [ 1.1314,  0.7993, -0.0759,  ...,  0.9245,  1.3507,  0.7078],
         [-0.2375, -0.1657, -0.2034,  ...,  0.4091,  1.1246,  0.5692]]],
       device='cuda:0', requires_grad=True)

In [13]:
fs_param[1]

tensor([[ 0.0385,  0.0989, -0.3344,  ..., -0.4580, -0.7559, -1.5160],
        [-0.4181,  0.1510, -0.2686,  ...,  0.0604,  0.4920,  1.7495],
        [ 1.5350, -0.7006, -0.4443,  ..., -0.0768, -1.3778, -0.2458],
        ...,
        [-0.1056,  1.5038,  0.8549,  ...,  0.7578,  1.1643,  0.4014],
        [-0.1056,  1.5038,  0.8549,  ...,  0.7578,  1.1643,  0.4014],
        [-0.1056,  1.5038,  0.8549,  ...,  0.7578,  1.1643,  0.4014]],
       device='cuda:0', requires_grad=True)

In [27]:
(hf_param[13] - fs_param[13][:13]).mean()

tensor(-1.0141e-06, device='cuda:0', grad_fn=<MeanBackward0>)